# -*- coding: utf-8 -*-
"""palindrome_checker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynj-7n6pC_vAZSswElPgWbdowu1NpsjF

Check if a word is a palindrome or not.
"""

def palindrome_checker (word):
    lowered = word.lower()
    reversed = lowered[::-1]
        
## if else code to check wheater a word is palindrome or not    

    if lowered == reversed:
        print("'" + word + "' is a Palindrome")
    else:
        print("'" + word + "' is NOT a Palindrome")

palindrome_checker('212')

palindrome_checker('098767890')

palindrome_checker('sentences')

palindrome_checker('racecar')